name: My first workflow 

on: [push]

jobs:
    my-first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "Hello, welcome to my first GitHub Actions workflow!"
            
            - name: List files in the repository
              run: ls

            - name: Read a file
              run: cat README.md
